// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkkiJlSw-Cg8tcJq69wO2wSIk-iWgm5is',
    appId: '1:674519245752:web:211658abfa2a754246654d',
    messagingSenderId: '674519245752',
    projectId: 'haseeb-project-3af66',
    authDomain: 'haseeb-project-3af66.firebaseapp.com',
    storageBucket: 'haseeb-project-3af66.appspot.com',
    measurementId: 'G-2NXDE6YJ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfAw_xgsbA6tVte7AbWx2MAaGuwLwzMik',
    appId: '1:674519245752:android:b83bbef36b6843c146654d',
    messagingSenderId: '674519245752',
    projectId: 'haseeb-project-3af66',
    storageBucket: 'haseeb-project-3af66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEnQcCUKt8iTfleapF91AECSLsrlza0Q',
    appId: '1:674519245752:ios:4905a5bcc40e1ec946654d',
    messagingSenderId: '674519245752',
    projectId: 'haseeb-project-3af66',
    storageBucket: 'haseeb-project-3af66.appspot.com',
    iosBundleId: 'com.example.hassebProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkkiJlSw-Cg8tcJq69wO2wSIk-iWgm5is',
    appId: '1:674519245752:web:2b6eacbdc1bacfeb46654d',
    messagingSenderId: '674519245752',
    projectId: 'haseeb-project-3af66',
    authDomain: 'haseeb-project-3af66.firebaseapp.com',
    storageBucket: 'haseeb-project-3af66.appspot.com',
    measurementId: 'G-YE0V1PEXX6',
  );
}
